(part "L101121MS02Q"
    (packageRef "L101021MS02Q")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "162")
    (property "Mouser_Part_Number" "611-L101121MS02Q")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/CK/L101121MS02Q?qs=LgMIjt8LuD8aORdKDdfKMg%3D%3D")
    (property "Manufacturer_Name" "C & K COMPONENTS")
    (property "Manufacturer_Part_Number" "L101121MS02Q")
    (property "Description" "Slide Switches SWITCH SLIDE SPST 4A 125VAC")
    (property "Datasheet_Link" "https://www.ckswitches.com/media/1423/l.pdf")
    (property "symbolName1" "L101121MS02Q")
)
